---
# tasks file for webserver
- name: install apache
  yum:
    name: "httpd"
    state: present
  # tags: packages

- name: install git
  yum:
    name: "git"
    state: present

- name: clone a repo
  git:
    repo: https://github.com/dybran/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  command: cp -r /var/www/html/html/ /var/www/

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  file:
    path: /var/www/html/html
